version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - yum update -y
      - yum install -y python3 python3-devel gcc freetds freetds-devel zip
      - curl -O https://bootstrap.pypa.io/get-pip.py
      - python3 get-pip.py
  build:
    commands:
      - mkdir -p python/lib/python3.9/site-packages
      - pip3 install --no-cache-dir --target=python/lib/python3.9/site-packages pandas pymssql
      - zip -r layer.zip python
artifacts:
  files:
    - layer.zip
